<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="15" total="48" passed="33">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="705239" started-at="2020-05-20T13:35:34Z" finished-at="2020-05-20T13:47:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="705239" started-at="2020-05-20T13:35:34Z" finished-at="2020-05-20T13:47:19Z">
      <class name="twc.Regression.TestCases.regressionTestCases">
        <test-method status="PASS" signature="Before_Test()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="Before_Test" is-config="true" duration-ms="550230" started-at="2020-05-20T19:05:34Z" finished-at="2020-05-20T19:14:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Before_Test -->
        <test-method status="FAIL" signature="C333210_Verify_cust_param_vw()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333210_Verify_cust_param_vw" duration-ms="4777" started-at="2020-05-20T19:14:44Z" finished-at="2020-05-20T19:14:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[vw Value not matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: vw Value not matched
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:473)
	at twc.Regression.TestCases.regressionTestCases.C333210_Verify_cust_param_vw(regressionTestCases.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333210_Verify_cust_param_vw -->
        <test-method status="PASS" signature="C333213_Verify_cust_param_aid()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333213_Verify_cust_param_aid" duration-ms="3961" started-at="2020-05-20T19:14:49Z" finished-at="2020-05-20T19:14:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333213_Verify_cust_param_aid -->
        <test-method status="PASS" signature="C333200_Verify_cust_param_ord()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333200_Verify_cust_param_ord" duration-ms="3344" started-at="2020-05-20T19:14:53Z" finished-at="2020-05-20T19:14:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333200_Verify_cust_param_ord -->
        <test-method status="FAIL" signature="C333235_Verify_cust_param_a()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333235_Verify_cust_param_a" duration-ms="3362" started-at="2020-05-20T19:14:56Z" finished-at="2020-05-20T19:14:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[a Value not matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: a Value not matched
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:530)
	at twc.Regression.TestCases.regressionTestCases.C333235_Verify_cust_param_a(regressionTestCases.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333235_Verify_cust_param_a -->
        <test-method status="FAIL" signature="C658714_Verify_cust_param_ch()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C658714_Verify_cust_param_ch" duration-ms="3480" started-at="2020-05-20T19:14:59Z" finished-at="2020-05-20T19:15:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ch Value not matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ch Value not matched
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:539)
	at twc.Regression.TestCases.regressionTestCases.C658714_Verify_cust_param_ch(regressionTestCases.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C658714_Verify_cust_param_ch -->
        <test-method status="FAIL" signature="C658715_Verify_cust_param_fam()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C658715_Verify_cust_param_fam" duration-ms="3360" started-at="2020-05-20T19:15:03Z" finished-at="2020-05-20T19:15:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[fam Value not matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: fam Value not matched
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:548)
	at twc.Regression.TestCases.regressionTestCases.C658715_Verify_cust_param_fam(regressionTestCases.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C658715_Verify_cust_param_fam -->
        <test-method status="FAIL" signature="C333236_Verify_cust_param_g()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333236_Verify_cust_param_g" duration-ms="3556" started-at="2020-05-20T19:15:06Z" finished-at="2020-05-20T19:15:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[g Value not matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: g Value not matched
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:557)
	at twc.Regression.TestCases.regressionTestCases.C333236_Verify_cust_param_g(regressionTestCases.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333236_Verify_cust_param_g -->
        <test-method status="FAIL" signature="C333225_Verify_cust_param_layer()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333225_Verify_cust_param_layer" duration-ms="3463" started-at="2020-05-20T19:15:10Z" finished-at="2020-05-20T19:15:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[layer Value not matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: layer Value not matched
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:566)
	at twc.Regression.TestCases.regressionTestCases.C333225_Verify_cust_param_layer(regressionTestCases.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333225_Verify_cust_param_layer -->
        <test-method status="FAIL" signature="C333204_Verify_cust_param_rmid()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333204_Verify_cust_param_rmid" duration-ms="3211" started-at="2020-05-20T19:15:13Z" finished-at="2020-05-20T19:15:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[rmid Value not matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: rmid Value not matched
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:575)
	at twc.Regression.TestCases.regressionTestCases.C333204_Verify_cust_param_rmid(regressionTestCases.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333204_Verify_cust_param_rmid -->
        <test-method status="PASS" signature="C333229_Verify_cust_param_faud()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333229_Verify_cust_param_faud" duration-ms="3183" started-at="2020-05-20T19:15:16Z" finished-at="2020-05-20T19:15:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333229_Verify_cust_param_faud -->
        <test-method status="PASS" signature="C658716_Verify_cust_param_tf()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C658716_Verify_cust_param_tf" duration-ms="2040" started-at="2020-05-20T19:15:20Z" finished-at="2020-05-20T19:15:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C658716_Verify_cust_param_tf -->
        <test-method status="PASS" signature="C333219_Verify_cust_param_ver()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333219_Verify_cust_param_ver" duration-ms="3414" started-at="2020-05-20T19:15:22Z" finished-at="2020-05-20T19:15:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333219_Verify_cust_param_ver -->
        <test-method status="FAIL" signature="C333230_Verify_cust_param_fgeo()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333230_Verify_cust_param_fgeo" duration-ms="3453" started-at="2020-05-20T19:15:25Z" finished-at="2020-05-20T19:15:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[fgeo Value not matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: fgeo Value not matched
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:347)
	at twc.Regression.TestCases.regressionTestCases.C333230_Verify_cust_param_fgeo(regressionTestCases.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333230_Verify_cust_param_fgeo -->
        <test-method status="FAIL" signature="C333226_Verify_cust_param_st()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333226_Verify_cust_param_st" duration-ms="3318" started-at="2020-05-20T19:15:28Z" finished-at="2020-05-20T19:15:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[st Value not matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: st Value not matched
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:292)
	at twc.Regression.TestCases.regressionTestCases.C333226_Verify_cust_param_st(regressionTestCases.java:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333226_Verify_cust_param_st -->
        <test-method status="PASS" signature="C333213_Verify_cust_param_adid()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333213_Verify_cust_param_adid" duration-ms="3541" started-at="2020-05-20T19:15:32Z" finished-at="2020-05-20T19:15:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333213_Verify_cust_param_adid -->
        <test-method status="PASS" signature="C333228_Verify_cust_param_wfxtg()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333228_Verify_cust_param_wfxtg" duration-ms="3688" started-at="2020-05-20T19:15:35Z" finished-at="2020-05-20T19:15:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333228_Verify_cust_param_wfxtg -->
        <test-method status="FAIL" signature="C333240_Verify_cust_param_zcs()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333240_Verify_cust_param_zcs" duration-ms="450" started-at="2020-05-20T19:15:39Z" finished-at="2020-05-20T19:15:39Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at twc.Regression.CustomParamValidation.CustomParamFunctions.validate_wfxtg_results(CustomParamFunctions.java:458)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:316)
	at twc.Regression.TestCases.regressionTestCases.C333240_Verify_cust_param_zcs(regressionTestCases.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333240_Verify_cust_param_zcs -->
        <test-method status="FAIL" signature="C333241_Verify_cust_param_nzcs()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333241_Verify_cust_param_nzcs" duration-ms="444" started-at="2020-05-20T19:15:39Z" finished-at="2020-05-20T19:15:40Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at twc.Regression.CustomParamValidation.CustomParamFunctions.validate_wfxtg_results(CustomParamFunctions.java:458)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:334)
	at twc.Regression.TestCases.regressionTestCases.C333241_Verify_cust_param_nzcs(regressionTestCases.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333241_Verify_cust_param_nzcs -->
        <test-method status="FAIL" signature="C333242_Verify_cust_param_hzcs()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333242_Verify_cust_param_hzcs" duration-ms="440" started-at="2020-05-20T19:15:40Z" finished-at="2020-05-20T19:15:40Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:326)
	at twc.Regression.TestCases.regressionTestCases.C333242_Verify_cust_param_hzcs(regressionTestCases.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333242_Verify_cust_param_hzcs -->
        <test-method status="FAIL" signature="C333214_Verify_cust_param_hlzip()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333214_Verify_cust_param_hlzip" duration-ms="466" started-at="2020-05-20T19:15:40Z" finished-at="2020-05-20T19:15:41Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:380)
	at twc.Regression.TestCases.regressionTestCases.C333214_Verify_cust_param_hlzip(regressionTestCases.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333214_Verify_cust_param_hlzip -->
        <test-method status="PASS" signature="C658712_Verify_cust_param_plat1()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C658712_Verify_cust_param_plat1" duration-ms="3399" started-at="2020-05-20T19:15:41Z" finished-at="2020-05-20T19:15:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C658712_Verify_cust_param_plat1 -->
        <test-method status="FAIL" signature="C333215_Verify_cust_param_ftl()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333215_Verify_cust_param_ftl" duration-ms="3307" started-at="2020-05-20T19:15:44Z" finished-at="2020-05-20T19:15:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ftl Value not matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ftl Value not matched
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:425)
	at twc.Regression.TestCases.regressionTestCases.C333215_Verify_cust_param_ftl(regressionTestCases.java:268)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333215_Verify_cust_param_ftl -->
        <test-method status="PASS" signature="C658711_Verify_cust_param_lang()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C658711_Verify_cust_param_lang" duration-ms="3272" started-at="2020-05-20T19:15:48Z" finished-at="2020-05-20T19:15:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C658711_Verify_cust_param_lang -->
        <test-method status="PASS" signature="C333218_Verify_cust_param_pos()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333218_Verify_cust_param_pos" duration-ms="3435" started-at="2020-05-20T19:15:51Z" finished-at="2020-05-20T19:15:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333218_Verify_cust_param_pos -->
        <test-method status="PASS" signature="C333205_Verify_cust_param_tile()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333205_Verify_cust_param_tile" duration-ms="3317" started-at="2020-05-20T19:15:54Z" finished-at="2020-05-20T19:15:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333205_Verify_cust_param_tile -->
        <test-method status="PASS" signature="C658713_Verify_cust_param_par()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C658713_Verify_cust_param_par" duration-ms="3366" started-at="2020-05-20T19:15:58Z" finished-at="2020-05-20T19:16:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C658713_Verify_cust_param_par -->
        <test-method status="PASS" signature="C344257_Verify_Video_Url_Parameter_cmsid()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C344257_Verify_Video_Url_Parameter_cmsid" duration-ms="766" started-at="2020-05-20T19:16:01Z" finished-at="2020-05-20T19:16:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C344257_Verify_Video_Url_Parameter_cmsid -->
        <test-method status="PASS" signature="C344258_Verify_Video_Url_Parameter_ttid()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C344258_Verify_Video_Url_Parameter_ttid" duration-ms="722" started-at="2020-05-20T19:16:02Z" finished-at="2020-05-20T19:16:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C344258_Verify_Video_Url_Parameter_ttid -->
        <test-method status="PASS" signature="C344260_Verify_Video_Url_Parameter_lnid()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C344260_Verify_Video_Url_Parameter_lnid" duration-ms="752" started-at="2020-05-20T19:16:02Z" finished-at="2020-05-20T19:16:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C344260_Verify_Video_Url_Parameter_lnid -->
        <test-method status="PASS" signature="C344259_Verify_Video_Url_Parameter_vid()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C344259_Verify_Video_Url_Parameter_vid" duration-ms="614" started-at="2020-05-20T19:16:03Z" finished-at="2020-05-20T19:16:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C344259_Verify_Video_Url_Parameter_vid -->
        <test-method status="PASS" signature="C344261_Verify_Video_Url_Parameter_iu()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C344261_Verify_Video_Url_Parameter_iu" duration-ms="786" started-at="2020-05-20T19:16:04Z" finished-at="2020-05-20T19:16:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C344261_Verify_Video_Url_Parameter_iu -->
        <test-method status="PASS" signature="C628160_Verify_Parameter_DyNght()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C628160_Verify_Parameter_DyNght" duration-ms="3719" started-at="2020-05-20T19:16:05Z" finished-at="2020-05-20T19:16:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C628160_Verify_Parameter_DyNght -->
        <test-method status="PASS" signature="C333208_Verify_cust_param_tmp()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333208_Verify_cust_param_tmp" duration-ms="5341" started-at="2020-05-20T19:16:08Z" finished-at="2020-05-20T19:16:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333208_Verify_cust_param_tmp -->
        <test-method status="PASS" signature="C333217_Verify_cust_param_tmpr()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333217_Verify_cust_param_tmpr" duration-ms="5077" started-at="2020-05-20T19:16:14Z" finished-at="2020-05-20T19:16:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333217_Verify_cust_param_tmpr -->
        <test-method status="PASS" signature="C333216_Verify_cust_param_cnd()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333216_Verify_cust_param_cnd" duration-ms="5256" started-at="2020-05-20T19:16:19Z" finished-at="2020-05-20T19:16:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333216_Verify_cust_param_cnd -->
        <test-method status="PASS" signature="C333207_Verify_cust_param_hmid()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333207_Verify_cust_param_hmid" duration-ms="4835" started-at="2020-05-20T19:16:24Z" finished-at="2020-05-20T19:16:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333207_Verify_cust_param_hmid -->
        <test-method status="PASS" signature="C333221_Verify_cust_param_wind()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333221_Verify_cust_param_wind" duration-ms="4789" started-at="2020-05-20T19:16:29Z" finished-at="2020-05-20T19:16:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333221_Verify_cust_param_wind -->
        <test-method status="PASS" signature="C333224_Verify_cust_param_uv()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333224_Verify_cust_param_uv" duration-ms="4831" started-at="2020-05-20T19:16:34Z" finished-at="2020-05-20T19:16:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333224_Verify_cust_param_uv -->
        <test-method status="PASS" signature="C333232_Verify_cust_param_fltmpc()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333232_Verify_cust_param_fltmpc" duration-ms="4985" started-at="2020-05-20T19:16:38Z" finished-at="2020-05-20T19:16:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333232_Verify_cust_param_fltmpc -->
        <test-method status="PASS" signature="C333239_Verify_cust_param_tmpc()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333239_Verify_cust_param_tmpc" duration-ms="4852" started-at="2020-05-20T19:16:43Z" finished-at="2020-05-20T19:16:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333239_Verify_cust_param_tmpc -->
        <test-method status="PASS" signature="C333202_Verify_cust_param_zip()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333202_Verify_cust_param_zip" duration-ms="4157" started-at="2020-05-20T19:16:48Z" finished-at="2020-05-20T19:16:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333202_Verify_cust_param_zip -->
        <test-method status="PASS" signature="C333203_Verify_cust_param_dma()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333203_Verify_cust_param_dma" duration-ms="4161" started-at="2020-05-20T19:16:52Z" finished-at="2020-05-20T19:16:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333203_Verify_cust_param_dma -->
        <test-method status="PASS" signature="C333209_Verify_cust_param_cc()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333209_Verify_cust_param_cc" duration-ms="4155" started-at="2020-05-20T19:16:57Z" finished-at="2020-05-20T19:17:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333209_Verify_cust_param_cc -->
        <test-method status="PASS" signature="C333212_Verify_cust_param_ct()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333212_Verify_cust_param_ct" duration-ms="3970" started-at="2020-05-20T19:17:01Z" finished-at="2020-05-20T19:17:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333212_Verify_cust_param_ct -->
        <test-method status="PASS" signature="C333232_Verify_cust_param_fhic()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333232_Verify_cust_param_fhic" duration-ms="5201" started-at="2020-05-20T19:17:05Z" finished-at="2020-05-20T19:17:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333232_Verify_cust_param_fhic -->
        <test-method status="PASS" signature="C333238_Verify_cust_param_floc()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333238_Verify_cust_param_floc" duration-ms="4830" started-at="2020-05-20T19:17:10Z" finished-at="2020-05-20T19:17:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333238_Verify_cust_param_floc -->
        <test-method status="FAIL" signature="C333211_Verify_cust_param_locale()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333211_Verify_cust_param_locale" duration-ms="454" started-at="2020-05-20T19:17:15Z" finished-at="2020-05-20T19:17:15Z">
          <exception class="org.json.simple.parser.ParseException">
            <full-stacktrace>
              <![CDATA[Unexpected token RIGHT SQUARE(]) at position 11065.
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at twc.Regression.CustomParamValidation.CustomParamFunctions.get_dsxcms_call_value(CustomParamFunctions.java:942)
	at twc.Regression.CustomParamValidation.CustomParamFunctions.validate_dsxcms_results(CustomParamFunctions.java:296)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:370)
	at twc.Regression.TestCases.regressionTestCases.C333211_Verify_cust_param_locale(regressionTestCases.java:465)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.simple.parser.ParseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333211_Verify_cust_param_locale -->
        <test-method status="PASS" signature="C333223_Verify_cust_param_sev()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="C333223_Verify_cust_param_sev" duration-ms="3626" started-at="2020-05-20T19:17:15Z" finished-at="2020-05-20T19:17:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333223_Verify_cust_param_sev -->
        <test-method status="PASS" signature="After_Test()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7ff09659]" name="After_Test" is-config="true" duration-ms="0" started-at="2020-05-20T19:17:19Z" finished-at="2020-05-20T19:17:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- After_Test -->
      </class> <!-- twc.Regression.TestCases.regressionTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
