<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" total="10" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1159134" started-at="2020-04-13T09:02:59Z" finished-at="2020-04-13T09:22:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1159134" started-at="2020-04-13T09:02:59Z" finished-at="2020-04-13T09:22:18Z">
      <class name="ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI">
        <test-method status="PASS" signature="Before_Test()[pri:0, instance:ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI@1d9bd4da]" name="Before_Test" is-config="true" duration-ms="350591" started-at="2020-04-13T14:32:59Z" finished-at="2020-04-13T14:38:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Before_Test -->
        <test-method status="FAIL" signature="Validating_Home_page_Ad()[pri:1, instance:ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI@1d9bd4da]" name="Validating_Home_page_Ad" duration-ms="66258" started-at="2020-04-13T14:38:50Z" finished-at="2020-04-13T14:39:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[home page ad not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: home page ad not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.HandleWithAppium.AppiumFunctions.Check_Home_ad(AppiumFunctions.java:1520)
	at ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI.Validating_Home_page_Ad(FeedAdVAlidationonUI.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validating_Home_page_Ad -->
        <test-method status="FAIL" signature="Validating_Dailyforecast_feed__card()[pri:4, instance:ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI@1d9bd4da]" name="Validating_Dailyforecast_feed__card" duration-ms="95830" started-at="2020-04-13T14:39:56Z" finished-at="2020-04-13T14:41:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[dailyforecast ad not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: dailyforecast ad not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.HandleWithAppium.AppiumFunctions.Check_dailyforecast_feedad(AppiumFunctions.java:1630)
	at ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI.Validating_Dailyforecast_feed__card(FeedAdVAlidationonUI.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validating_Dailyforecast_feed__card -->
        <test-method status="PASS" signature="Extended_Deatail_MapsPage_Ad()[pri:5, instance:ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI@1d9bd4da]" name="Extended_Deatail_MapsPage_Ad" duration-ms="126243" started-at="2020-04-13T14:41:32Z" finished-at="2020-04-13T14:43:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Extended_Deatail_MapsPage_Ad -->
        <test-method status="FAIL" signature="Validating_Radar_Maps_feed__card()[pri:6, instance:ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI@1d9bd4da]" name="Validating_Radar_Maps_feed__card" duration-ms="75445" started-at="2020-04-13T14:43:38Z" finished-at="2020-04-13T14:44:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Radar&Maps ad not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Radar&Maps ad not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.HandleWithAppium.AppiumFunctions.Check_feed2_ad(AppiumFunctions.java:413)
	at ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI.Validating_Radar_Maps_feed__card(FeedAdVAlidationonUI.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validating_Radar_Maps_feed__card -->
        <test-method status="PASS" signature="Validating_Health_and_Activities_feed__card()[pri:7, instance:ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI@1d9bd4da]" name="Validating_Health_and_Activities_feed__card" duration-ms="23119" started-at="2020-04-13T14:44:54Z" finished-at="2020-04-13T14:45:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validating_Health_and_Activities_feed__card -->
        <test-method status="FAIL" signature="Extended_Today_datailpage_Ad()[pri:8, instance:ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI@1d9bd4da]" name="Extended_Today_datailpage_Ad" duration-ms="182539" started-at="2020-04-13T14:45:17Z" finished-at="2020-04-13T14:48:19Z">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.61 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.51.0', revision: '1af067dbcaedd7d2ab9af5151fc471d363d97193', time: '2016-02-05 11:20:57'
System info: host: 'Aswinikumars-MacBook-Pro.local', ip: '192.168.1.4', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_181'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.weather.Weather, statBarHeight=98, noReset=true, viewportRect={top=98, left=0, width=1440, height=2614}, deviceName=803KPXV1599674, platform=LINUX, deviceUDID=803KPXV1599674, desired={app=/Users/aswinikumar/Documents/adsandroid-automation-master/Android_ARMS_Automation/APKFile/app-google-debug-7122.apk, appPackage=com.weather.Weather, appActivity=com.weather.Weather.app.SplashScreenActivity, appium-version=1.4.13, noReset=true, newCommandTimeout=100000, platformVersion=10.0, platformName=Android, deviceName=Android}, appium-version=1.4.13, newCommandTimeout=100000, platformVersion=10, webStorageEnabled=false, takesScreenshot=true, javascriptEnabled=true, platformName=Android, deviceApiLevel=29, deviceManufacturer=Google, app=/Users/aswinikumar/Documents/adsandroid-automation-master/Android_ARMS_Automation/APKFile/app-google-debug-7122.apk, deviceScreenSize=1440x2880, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, appActivity=com.weather.Weather.app.SplashScreenActivity, pixelRatio=3.5, locationContextEnabled=false, deviceScreenDensity=560, deviceModel=Pixel 2 XL}]
Session ID: 41a422a3-05f6-4e2b-8d12-87d6ef200d11
*** Element info: {Using=accessibility id, value=Navigate up}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.61 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.51.0', revision: '1af067dbcaedd7d2ab9af5151fc471d363d97193', time: '2016-02-05 11:20:57'
System info: host: 'Aswinikumars-MacBook-Pro.local', ip: '192.168.1.4', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_181'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.weather.Weather, statBarHeight=98, noReset=true, viewportRect={top=98, left=0, width=1440, height=2614}, deviceName=803KPXV1599674, platform=LINUX, deviceUDID=803KPXV1599674, desired={app=/Users/aswinikumar/Documents/adsandroid-automation-master/Android_ARMS_Automation/APKFile/app-google-debug-7122.apk, appPackage=com.weather.Weather, appActivity=com.weather.Weather.app.SplashScreenActivity, appium-version=1.4.13, noReset=true, newCommandTimeout=100000, platformVersion=10.0, platformName=Android, deviceName=Android}, appium-version=1.4.13, newCommandTimeout=100000, platformVersion=10, webStorageEnabled=false, takesScreenshot=true, javascriptEnabled=true, platformName=Android, deviceApiLevel=29, deviceManufacturer=Google, app=/Users/aswinikumar/Documents/adsandroid-automation-master/Android_ARMS_Automation/APKFile/app-google-debug-7122.apk, deviceScreenSize=1440x2880, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, appActivity=com.weather.Weather.app.SplashScreenActivity, pixelRatio=3.5, locationContextEnabled=false, deviceScreenDensity=560, deviceModel=Pixel 2 XL}]
Session ID: 41a422a3-05f6-4e2b-8d12-87d6ef200d11
*** Element info: {Using=accessibility id, value=Navigate up}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByAccessibilityId(DefaultGenericMobileDriver.java:144)
	at io.appium.java_client.AppiumDriver.findElementByAccessibilityId(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementByAccessibilityId(AndroidDriver.java:1)
	at twc.Automation.HandleWithApp.AppFunctions.clickOnBackArrowElement(AppFunctions.java:1729)
	at twc.Automation.HandleWithAppium.AppiumFunctions.Check_submodules_Today_ad(AppiumFunctions.java:721)
	at ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI.Extended_Today_datailpage_Ad(FeedAdVAlidationonUI.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Extended_Today_datailpage_Ad -->
        <test-method status="FAIL" signature="Validating_Airpollution_feed_card()[pri:12, instance:ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI@1d9bd4da]" name="Validating_Airpollution_feed_card" duration-ms="75093" started-at="2020-04-13T14:48:19Z" finished-at="2020-04-13T14:49:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Airpollution feed card ad not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Airpollution feed card ad not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.HandleWithAppium.AppiumFunctions.Check_Airpollution_feedcard(AppiumFunctions.java:620)
	at ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI.Validating_Airpollution_feed_card(FeedAdVAlidationonUI.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validating_Airpollution_feed_card -->
        <test-method status="FAIL" signature="Validating_seasonalhub_feed__card()[pri:13, instance:ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI@1d9bd4da]" name="Validating_seasonalhub_feed__card" duration-ms="79455" started-at="2020-04-13T14:49:35Z" finished-at="2020-04-13T14:50:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[seasonalhub ad not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: seasonalhub ad not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.HandleWithAppium.AppiumFunctions.Check_seasonalhub_feedad(AppiumFunctions.java:1730)
	at ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI.Validating_seasonalhub_feed__card(FeedAdVAlidationonUI.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validating_seasonalhub_feed__card -->
        <test-method status="FAIL" signature="Extended_hourly_page_Ad()[pri:15, instance:ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI@1d9bd4da]" name="Extended_hourly_page_Ad" duration-ms="7498" started-at="2020-04-13T14:50:54Z" finished-at="2020-04-13T14:51:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Hourly submodule ad is not  present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Hourly submodule ad is not  present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.HandleWithAppium.AppiumFunctions.Check_submodules_Hourly_ad(AppiumFunctions.java:760)
	at ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI.Extended_hourly_page_Ad(FeedAdVAlidationonUI.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Extended_hourly_page_Ad -->
        <test-method status="PASS" signature="Extended_Maps_Radar_page_Ad()[pri:17, instance:ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI@1d9bd4da]" name="Extended_Maps_Radar_page_Ad" duration-ms="46623" started-at="2020-04-13T14:51:01Z" finished-at="2020-04-13T14:51:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Extended_Maps_Radar_page_Ad -->
        <test-method status="PASS" signature="End_Test()[pri:0, instance:ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI@1d9bd4da]" name="End_Test" is-config="true" duration-ms="30187" started-at="2020-04-13T14:51:48Z" finished-at="2020-04-13T14:52:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- End_Test -->
      </class> <!-- ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
